Repository FotonTech/NFoTon, pull requests merged in 2021-06, with the labels that each got.

#34 Chore/commitlint
  .husky/.gitignore
  .husky/commit-msg
  commitlint.config.js
  package.json
  packages/frontend/src/components/Hello/index.tsx
  yarn-error.log
  yarn.lock
Labels: config

#40 chore: adds prettier and eslint to the project
  .vscode/settings.json
  packages/frontend/.eslintrc.js
  packages/frontend/.prettierrc
  packages/frontend/package.json
  packages/frontend/src/components/Hello/index.stories.tsx
  packages/frontend/src/components/Hello/index.tsx
  packages/frontend/src/components/Hello/styles.ts
  packages/frontend/src/pages/_app.tsx
  packages/frontend/src/pages/_document.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/tsconfig.json
  yarn.lock
Labels: config

#41 feat: adding theme configuration
  packages/frontend/src/components/Hello/index.tsx
  packages/frontend/src/components/Hello/styles.ts
  packages/frontend/src/hooks/useTheme.tsx
  packages/frontend/src/pages/_app.tsx
  packages/frontend/src/pages/_document.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/src/styles/globalStyles.ts
  packages/frontend/src/theme/colors.ts
  packages/frontend/src/theme/index.ts
  packages/frontend/src/types/index.d.ts
  packages/frontend/src/utils/storage.ts
  packages/frontend/tsconfig.json
Labels: config

#52 Feat/Add themes to storybook
  packages/frontend/.storybook/main.js
  packages/frontend/.storybook/preview.js
  packages/frontend/package.json
Labels: config

#55 Merge branch develop into main
  .vscode/settings.json
  packages/frontend/.eslintrc.js
  packages/frontend/.prettierrc
  packages/frontend/.storybook/main.js
  packages/frontend/.storybook/preview.js
  packages/frontend/package.json
  packages/frontend/src/components/Hello/index.stories.tsx
  packages/frontend/src/components/Hello/index.tsx
  packages/frontend/src/components/Hello/styles.ts
  packages/frontend/src/hooks/useTheme.tsx
  packages/frontend/src/pages/_app.tsx
  packages/frontend/src/pages/_document.tsx
  packages/frontend/src/pages/index.tsx
  packages/frontend/src/styles/globalStyles.ts
  packages/frontend/src/theme/colors.ts
  packages/frontend/src/theme/index.ts
  packages/frontend/src/types/index.d.ts
  packages/frontend/src/utils/storage.ts
  packages/frontend/tsconfig.json
  yarn-error.log
  yarn.lock
Labels: config, enhancement

#59 Docs/new contributor - allanneto
  .all-contributorsrc
Labels: documentation

#61 feat: adding react-icons and burger-icon element to the project
  packages/frontend/package.json
  packages/frontend/src/components/Hello/styles.ts
  packages/frontend/src/elements/BurgerIcon/index.stories.tsx
  packages/frontend/src/elements/BurgerIcon/index.tsx
  packages/frontend/src/elements/BurgerIcon/styles.ts
  packages/frontend/src/theme/index.ts
  packages/frontend/src/types/index.d.ts
Labels: enhancement

#62 feat: add Logo Component and change storybook config to show imgs cor…
  packages/frontend/.storybook/preview.js
  packages/frontend/package.json
  packages/frontend/public/logo.png
  packages/frontend/src/elements/Logo/index.stories.tsx
  packages/frontend/src/elements/Logo/index.tsx
  packages/frontend/src/elements/Logo/styles.ts
  packages/frontend/src/theme/index.ts
  packages/frontend/src/types/index.d.ts
  yarn.lock
Labels: enhancement

#64 Chore/theme
  packages/frontend/.storybook/preview.js
  packages/frontend/src/components/Hello/index.tsx
  packages/frontend/src/components/Hello/styles.ts
  packages/frontend/src/elements/BurgerIcon/index.tsx
  packages/frontend/src/elements/BurgerIcon/styles.ts
  packages/frontend/src/elements/Logo/styles.ts
  packages/frontend/src/hooks/useTheme.tsx
  packages/frontend/src/theme/index.ts
  packages/frontend/src/types/index.d.ts
  packages/frontend/src/utils/storage.ts
  yarn.lock
Labels: config

#65 feat: adding theme to the example component
  packages/frontend/src/components/Hello/styles.ts
  packages/frontend/src/hooks/useTheme.tsx
Labels: config, enhancement

#68 Feat/notifications
  packages/frontend/package.json
  packages/frontend/public/notification-badge.svg
  packages/frontend/public/notification-img-placeholder.jpg
  packages/frontend/src/components/Header/index.stories.tsx
  packages/frontend/src/components/Header/index.tsx
  packages/frontend/src/components/Header/styles.ts
  packages/frontend/src/components/Media/index.tsx
  packages/frontend/src/components/Notifications/index.stories.tsx
  packages/frontend/src/components/Notifications/index.tsx
  packages/frontend/src/components/Notifications/styles.ts
  packages/frontend/src/components/Notifications/styles/dropdown.ts
  packages/frontend/src/components/Notifications/styles/notification-button.ts
  packages/frontend/src/components/Notifications/styles/notification.ts
  packages/frontend/src/elements/BurgerIcon/styles.ts
  packages/frontend/src/mock/notifications.ts
  packages/frontend/src/theme/breakpoints.ts
  packages/frontend/src/theme/index.ts
  packages/frontend/src/types/index.d.ts
  yarn.lock
Labels: config, enhancement, frontend
